---
egi:
  ims:
    # To access the tool(s) users need to be member of the VO and have the appropriate role
    # VO managers will be able to assign/revoke the role to/from VO members
    vo: vo.tools.egi.eu
    roles:
      process-owner: slm-owner
      process-manager: slm-manager
      catalog-manager: slm-catalog
      report-owner: slm-report
      ua-owner: slm-ua
      sla-owner: slm-sla
      ola-owner: slm-ola
  qos:
    quantiles: [0.95]
    slos: [500] # SLOs in milliseconds

quarkus:
  application:
    name: capacity-registry-api
  oidc:
    auth-server-url: https://aai-demo.egi.eu/auth/realms/egi
    application-type: service
    client-id: egi-capacity-registry
    credentials: secret
    #discovery-enabled: false
    #introspection-path: /protocol/openid-connect/token/introspect
    roles:
      source: userinfo
#    token-cache:
#      max-size: 1000              # Set to > 0 to enable cache
#      time-to-live: 5M            # How long a cache entry can be valid
#      clean-up-timer-interval: 1M # Enable cleanup timer
  log:
    level: INFO
    min-level: DEBUG
    console:
      enable: true
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
      json:
        ~: false
    file:
      enable: true
      path: logs/api.json
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
      rotation:
        max-file-size: 1M
        max-backup-index: 10
      json:
        ~: true
    category:
      "io.quarkus.oidc.runtime.OidcRecorder": # Initialization
        level: TRACE
        min-level: TRACE
      "io.quarkus.oidc.runtime.OidcProvider": # Verification
        level: TRACE
        min-level: TRACE
  otel:
    enabled: false
    exporter:
      otlp:
        traces:
          legacy-endpoint: http://localhost:4317
  micrometer:
    enabled: true
    export:
      prometheus:
        path: /metrics
    binder:
      http-client:
        ignore-patterns: /.+
      http-server:
        ignore-patterns: /metrics
  swagger-ui:
    always-include: true
    path: swagger-ui
    theme: flattop
    urls:
      default: /openapi
    urls-primary-name: default
  smallrye-openapi:
    path: /openapi
    info-version: 1.0.3
    security-scheme-name: OIDC
    security-scheme-description: OpenID Connect access token issued by EGI Check-In
    security-scheme: jwt
    jwt-security-scheme-value: bearer
    jwt-bearer-format: JWT
  jackson:
    fail-on-unknown-properties: false
  http:
    port: 8081
    auth:
      basic: false
    cors:
      ~: true
    proxy:
      proxy-address-forwarding: true
      allow-x-forwarded: true
      enable-forwarded-host: true
    access-log:
      enabled: false
      pattern: "%r -> %s\n%{ALL_REQUEST_HEADERS}\n"
      log-to-file: true
      base-file-name: api-http
      log-directory: logs
  tls:
    trust-all: false
  test:
    continuous-testing: disabled
